server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html
      
  thymeleaf:
      enabled: false
      
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=chat"
    username: postgres
    password: Magestade12
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
